CREATE TABLE IF NOT EXISTS telegram_order_sessions (
 telegram_user_id BIGINT NOT NULL PRIMARY KEY, chat_id BIGINT NOT NULL, step VARCHAR(30) NOT NULL,
 data_json TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS telegram_order_contacts (
 order_no VARCHAR(100) NOT NULL PRIMARY KEY, telegram_user_id BIGINT NOT NULL, chat_id BIGINT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE withdrawal_requests ADD COLUMN tx_hash VARCHAR(66) NULL, ADD COLUMN verification_error VARCHAR(255) NULL;
