CREATE TABLE IF NOT EXISTS telegram_order_sessions (
  telegram_user_id BIGINT NOT NULL PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  step VARCHAR(30) NOT NULL,
  data_json TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);